// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ribpapi.proto

/*
Package ribpapi is a generated protocol buffer package.

It is generated from these files:
	ribpapi.proto

It has these top-level messages:
	FFPacketRequest
	SendFFPacketReply
*/
package ribpapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FFPacketRequest struct {
	Ifname string `protobuf:"bytes,1,opt,name=ifname" json:"ifname,omitempty"`
}

func (m *FFPacketRequest) Reset()                    { *m = FFPacketRequest{} }
func (m *FFPacketRequest) String() string            { return proto.CompactTextString(m) }
func (*FFPacketRequest) ProtoMessage()               {}
func (*FFPacketRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FFPacketRequest) GetIfname() string {
	if m != nil {
		return m.Ifname
	}
	return ""
}

type SendFFPacketReply struct {
}

func (m *SendFFPacketReply) Reset()                    { *m = SendFFPacketReply{} }
func (m *SendFFPacketReply) String() string            { return proto.CompactTextString(m) }
func (*SendFFPacketReply) ProtoMessage()               {}
func (*SendFFPacketReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*FFPacketRequest)(nil), "ribpapi.FFPacketRequest")
	proto.RegisterType((*SendFFPacketReply)(nil), "ribpapi.SendFFPacketReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RIBPApi service

type RIBPApiClient interface {
	SendFFPacket(ctx context.Context, in *FFPacketRequest, opts ...grpc.CallOption) (*SendFFPacketReply, error)
}

type rIBPApiClient struct {
	cc *grpc.ClientConn
}

func NewRIBPApiClient(cc *grpc.ClientConn) RIBPApiClient {
	return &rIBPApiClient{cc}
}

func (c *rIBPApiClient) SendFFPacket(ctx context.Context, in *FFPacketRequest, opts ...grpc.CallOption) (*SendFFPacketReply, error) {
	out := new(SendFFPacketReply)
	err := grpc.Invoke(ctx, "/ribpapi.RIBPApi/SendFFPacket", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RIBPApi service

type RIBPApiServer interface {
	SendFFPacket(context.Context, *FFPacketRequest) (*SendFFPacketReply, error)
}

func RegisterRIBPApiServer(s *grpc.Server, srv RIBPApiServer) {
	s.RegisterService(&_RIBPApi_serviceDesc, srv)
}

func _RIBPApi_SendFFPacket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FFPacketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RIBPApiServer).SendFFPacket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ribpapi.RIBPApi/SendFFPacket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RIBPApiServer).SendFFPacket(ctx, req.(*FFPacketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RIBPApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ribpapi.RIBPApi",
	HandlerType: (*RIBPApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendFFPacket",
			Handler:    _RIBPApi_SendFFPacket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ribpapi.proto",
}

func init() { proto.RegisterFile("ribpapi.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0xca, 0x4c, 0x2a,
	0x48, 0x2c, 0xc8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x34, 0xb9,
	0xf8, 0xdd, 0xdc, 0x02, 0x12, 0x93, 0xb3, 0x53, 0x4b, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b,
	0x84, 0xc4, 0xb8, 0xd8, 0x32, 0xd3, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0xa0, 0x3c, 0x25, 0x61, 0x2e, 0xc1, 0xe0, 0xd4, 0xbc, 0x14, 0x84, 0xf2, 0x82, 0x9c, 0x4a,
	0xa3, 0x40, 0x2e, 0xf6, 0x20, 0x4f, 0xa7, 0x00, 0xc7, 0x82, 0x4c, 0x21, 0x37, 0x2e, 0x1e, 0x64,
	0x79, 0x21, 0x09, 0x3d, 0x98, 0x9d, 0x68, 0x36, 0x48, 0x49, 0xc1, 0x65, 0x30, 0x0c, 0x54, 0x62,
	0x48, 0x62, 0x03, 0x3b, 0xd1, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x54, 0x9e, 0x86, 0xb3,
	0x00, 0x00, 0x00,
}
