# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nlalink.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nlalink.proto',
  package='nlalink',
  syntax='proto3',
  serialized_pb=_b('\n\rnlalink.proto\x12\x07nlalink\"\x12\n\x04Node\x12\n\n\x02ip\x18\x01 \x01(\x0c\"J\n\x03Vpn\x12\n\n\x02ip\x18\x01 \x01(\x0c\x12\x0c\n\x04mask\x18\x02 \x01(\x0c\x12\n\n\x02gw\x18\x03 \x01(\x0c\x12\r\n\x05label\x18\x04 \x01(\r\x12\x0e\n\x06vpn_gw\x18\x05 \x01(\x0c\x62\x06proto3')
)




_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='nlalink.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='nlalink.Node.ip', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=44,
)


_VPN = _descriptor.Descriptor(
  name='Vpn',
  full_name='nlalink.Vpn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='nlalink.Vpn.ip', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mask', full_name='nlalink.Vpn.mask', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gw', full_name='nlalink.Vpn.gw', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='nlalink.Vpn.label', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vpn_gw', full_name='nlalink.Vpn.vpn_gw', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['Vpn'] = _VPN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), dict(
  DESCRIPTOR = _NODE,
  __module__ = 'nlalink_pb2'
  # @@protoc_insertion_point(class_scope:nlalink.Node)
  ))
_sym_db.RegisterMessage(Node)

Vpn = _reflection.GeneratedProtocolMessageType('Vpn', (_message.Message,), dict(
  DESCRIPTOR = _VPN,
  __module__ = 'nlalink_pb2'
  # @@protoc_insertion_point(class_scope:nlalink.Vpn)
  ))
_sym_db.RegisterMessage(Vpn)


# @@protoc_insertion_point(module_scope)
