// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vswapi.proto

package vswapi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ModIfnameRequest_Cmd int32

const (
	ModIfnameRequest_NOP    ModIfnameRequest_Cmd = 0
	ModIfnameRequest_ADD    ModIfnameRequest_Cmd = 1
	ModIfnameRequest_REG    ModIfnameRequest_Cmd = 2
	ModIfnameRequest_DELETE ModIfnameRequest_Cmd = 3
	ModIfnameRequest_SYNC   ModIfnameRequest_Cmd = 4
)

var ModIfnameRequest_Cmd_name = map[int32]string{
	0: "NOP",
	1: "ADD",
	2: "REG",
	3: "DELETE",
	4: "SYNC",
}

var ModIfnameRequest_Cmd_value = map[string]int32{
	"NOP":    0,
	"ADD":    1,
	"REG":    2,
	"DELETE": 3,
	"SYNC":   4,
}

func (x ModIfnameRequest_Cmd) String() string {
	return proto.EnumName(ModIfnameRequest_Cmd_name, int32(x))
}

func (ModIfnameRequest_Cmd) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0b810c7445c1840d, []int{0, 0}
}

type ModLinkRequest_Cmd int32

const (
	ModLinkRequest_NOP  ModLinkRequest_Cmd = 0
	ModLinkRequest_UP   ModLinkRequest_Cmd = 1
	ModLinkRequest_DOWN ModLinkRequest_Cmd = 2
)

var ModLinkRequest_Cmd_name = map[int32]string{
	0: "NOP",
	1: "UP",
	2: "DOWN",
}

var ModLinkRequest_Cmd_value = map[string]int32{
	"NOP":  0,
	"UP":   1,
	"DOWN": 2,
}

func (x ModLinkRequest_Cmd) String() string {
	return proto.EnumName(ModLinkRequest_Cmd_name, int32(x))
}

func (ModLinkRequest_Cmd) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0b810c7445c1840d, []int{4, 0}
}

type ModIfnameRequest struct {
	Cmd                  ModIfnameRequest_Cmd `protobuf:"varint,1,opt,name=cmd,proto3,enum=vswapi.ModIfnameRequest_Cmd" json:"cmd,omitempty"`
	Ifname               string               `protobuf:"bytes,2,opt,name=ifname,proto3" json:"ifname,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ModIfnameRequest) Reset()         { *m = ModIfnameRequest{} }
func (m *ModIfnameRequest) String() string { return proto.CompactTextString(m) }
func (*ModIfnameRequest) ProtoMessage()    {}
func (*ModIfnameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b810c7445c1840d, []int{0}
}

func (m *ModIfnameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModIfnameRequest.Unmarshal(m, b)
}
func (m *ModIfnameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModIfnameRequest.Marshal(b, m, deterministic)
}
func (m *ModIfnameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModIfnameRequest.Merge(m, src)
}
func (m *ModIfnameRequest) XXX_Size() int {
	return xxx_messageInfo_ModIfnameRequest.Size(m)
}
func (m *ModIfnameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModIfnameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModIfnameRequest proto.InternalMessageInfo

func (m *ModIfnameRequest) GetCmd() ModIfnameRequest_Cmd {
	if m != nil {
		return m.Cmd
	}
	return ModIfnameRequest_NOP
}

func (m *ModIfnameRequest) GetIfname() string {
	if m != nil {
		return m.Ifname
	}
	return ""
}

type ModIfnameReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModIfnameReply) Reset()         { *m = ModIfnameReply{} }
func (m *ModIfnameReply) String() string { return proto.CompactTextString(m) }
func (*ModIfnameReply) ProtoMessage()    {}
func (*ModIfnameReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b810c7445c1840d, []int{1}
}

func (m *ModIfnameReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModIfnameReply.Unmarshal(m, b)
}
func (m *ModIfnameReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModIfnameReply.Marshal(b, m, deterministic)
}
func (m *ModIfnameReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModIfnameReply.Merge(m, src)
}
func (m *ModIfnameReply) XXX_Size() int {
	return xxx_messageInfo_ModIfnameReply.Size(m)
}
func (m *ModIfnameReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ModIfnameReply.DiscardUnknown(m)
}

var xxx_messageInfo_ModIfnameReply proto.InternalMessageInfo

type GetIfnamesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIfnamesRequest) Reset()         { *m = GetIfnamesRequest{} }
func (m *GetIfnamesRequest) String() string { return proto.CompactTextString(m) }
func (*GetIfnamesRequest) ProtoMessage()    {}
func (*GetIfnamesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b810c7445c1840d, []int{2}
}

func (m *GetIfnamesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIfnamesRequest.Unmarshal(m, b)
}
func (m *GetIfnamesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIfnamesRequest.Marshal(b, m, deterministic)
}
func (m *GetIfnamesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIfnamesRequest.Merge(m, src)
}
func (m *GetIfnamesRequest) XXX_Size() int {
	return xxx_messageInfo_GetIfnamesRequest.Size(m)
}
func (m *GetIfnamesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIfnamesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIfnamesRequest proto.InternalMessageInfo

type GetIfnamesReply struct {
	Ifname               string   `protobuf:"bytes,1,opt,name=ifname,proto3" json:"ifname,omitempty"`
	Kind                 string   `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIfnamesReply) Reset()         { *m = GetIfnamesReply{} }
func (m *GetIfnamesReply) String() string { return proto.CompactTextString(m) }
func (*GetIfnamesReply) ProtoMessage()    {}
func (*GetIfnamesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b810c7445c1840d, []int{3}
}

func (m *GetIfnamesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIfnamesReply.Unmarshal(m, b)
}
func (m *GetIfnamesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIfnamesReply.Marshal(b, m, deterministic)
}
func (m *GetIfnamesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIfnamesReply.Merge(m, src)
}
func (m *GetIfnamesReply) XXX_Size() int {
	return xxx_messageInfo_GetIfnamesReply.Size(m)
}
func (m *GetIfnamesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIfnamesReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetIfnamesReply proto.InternalMessageInfo

func (m *GetIfnamesReply) GetIfname() string {
	if m != nil {
		return m.Ifname
	}
	return ""
}

func (m *GetIfnamesReply) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

type ModLinkRequest struct {
	Cmd                  ModLinkRequest_Cmd `protobuf:"varint,1,opt,name=cmd,proto3,enum=vswapi.ModLinkRequest_Cmd" json:"cmd,omitempty"`
	Ifname               string             `protobuf:"bytes,2,opt,name=ifname,proto3" json:"ifname,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ModLinkRequest) Reset()         { *m = ModLinkRequest{} }
func (m *ModLinkRequest) String() string { return proto.CompactTextString(m) }
func (*ModLinkRequest) ProtoMessage()    {}
func (*ModLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b810c7445c1840d, []int{4}
}

func (m *ModLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModLinkRequest.Unmarshal(m, b)
}
func (m *ModLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModLinkRequest.Marshal(b, m, deterministic)
}
func (m *ModLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModLinkRequest.Merge(m, src)
}
func (m *ModLinkRequest) XXX_Size() int {
	return xxx_messageInfo_ModLinkRequest.Size(m)
}
func (m *ModLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModLinkRequest proto.InternalMessageInfo

func (m *ModLinkRequest) GetCmd() ModLinkRequest_Cmd {
	if m != nil {
		return m.Cmd
	}
	return ModLinkRequest_NOP
}

func (m *ModLinkRequest) GetIfname() string {
	if m != nil {
		return m.Ifname
	}
	return ""
}

type ModLinkReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModLinkReply) Reset()         { *m = ModLinkReply{} }
func (m *ModLinkReply) String() string { return proto.CompactTextString(m) }
func (*ModLinkReply) ProtoMessage()    {}
func (*ModLinkReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b810c7445c1840d, []int{5}
}

func (m *ModLinkReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModLinkReply.Unmarshal(m, b)
}
func (m *ModLinkReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModLinkReply.Marshal(b, m, deterministic)
}
func (m *ModLinkReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModLinkReply.Merge(m, src)
}
func (m *ModLinkReply) XXX_Size() int {
	return xxx_messageInfo_ModLinkReply.Size(m)
}
func (m *ModLinkReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ModLinkReply.DiscardUnknown(m)
}

var xxx_messageInfo_ModLinkReply proto.InternalMessageInfo

type GetLinksRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLinksRequest) Reset()         { *m = GetLinksRequest{} }
func (m *GetLinksRequest) String() string { return proto.CompactTextString(m) }
func (*GetLinksRequest) ProtoMessage()    {}
func (*GetLinksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b810c7445c1840d, []int{6}
}

func (m *GetLinksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLinksRequest.Unmarshal(m, b)
}
func (m *GetLinksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLinksRequest.Marshal(b, m, deterministic)
}
func (m *GetLinksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLinksRequest.Merge(m, src)
}
func (m *GetLinksRequest) XXX_Size() int {
	return xxx_messageInfo_GetLinksRequest.Size(m)
}
func (m *GetLinksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLinksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLinksRequest proto.InternalMessageInfo

type GetLinksReply struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLinksReply) Reset()         { *m = GetLinksReply{} }
func (m *GetLinksReply) String() string { return proto.CompactTextString(m) }
func (*GetLinksReply) ProtoMessage()    {}
func (*GetLinksReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b810c7445c1840d, []int{7}
}

func (m *GetLinksReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLinksReply.Unmarshal(m, b)
}
func (m *GetLinksReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLinksReply.Marshal(b, m, deterministic)
}
func (m *GetLinksReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLinksReply.Merge(m, src)
}
func (m *GetLinksReply) XXX_Size() int {
	return xxx_messageInfo_GetLinksReply.Size(m)
}
func (m *GetLinksReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLinksReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetLinksReply proto.InternalMessageInfo

func (m *GetLinksReply) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *GetLinksReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetStatsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatsRequest) Reset()         { *m = GetStatsRequest{} }
func (m *GetStatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatsRequest) ProtoMessage()    {}
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b810c7445c1840d, []int{8}
}

func (m *GetStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatsRequest.Unmarshal(m, b)
}
func (m *GetStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatsRequest.Marshal(b, m, deterministic)
}
func (m *GetStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatsRequest.Merge(m, src)
}
func (m *GetStatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatsRequest.Size(m)
}
func (m *GetStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatsRequest proto.InternalMessageInfo

type GetStatsReply struct {
	Group                string            `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Values               map[string]uint64 `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetStatsReply) Reset()         { *m = GetStatsReply{} }
func (m *GetStatsReply) String() string { return proto.CompactTextString(m) }
func (*GetStatsReply) ProtoMessage()    {}
func (*GetStatsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b810c7445c1840d, []int{9}
}

func (m *GetStatsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatsReply.Unmarshal(m, b)
}
func (m *GetStatsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatsReply.Marshal(b, m, deterministic)
}
func (m *GetStatsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatsReply.Merge(m, src)
}
func (m *GetStatsReply) XXX_Size() int {
	return xxx_messageInfo_GetStatsReply.Size(m)
}
func (m *GetStatsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatsReply proto.InternalMessageInfo

func (m *GetStatsReply) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *GetStatsReply) GetValues() map[string]uint64 {
	if m != nil {
		return m.Values
	}
	return nil
}

type SaveConfigRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveConfigRequest) Reset()         { *m = SaveConfigRequest{} }
func (m *SaveConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SaveConfigRequest) ProtoMessage()    {}
func (*SaveConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b810c7445c1840d, []int{10}
}

func (m *SaveConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveConfigRequest.Unmarshal(m, b)
}
func (m *SaveConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveConfigRequest.Marshal(b, m, deterministic)
}
func (m *SaveConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveConfigRequest.Merge(m, src)
}
func (m *SaveConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SaveConfigRequest.Size(m)
}
func (m *SaveConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveConfigRequest proto.InternalMessageInfo

type SaveConfigReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveConfigReply) Reset()         { *m = SaveConfigReply{} }
func (m *SaveConfigReply) String() string { return proto.CompactTextString(m) }
func (*SaveConfigReply) ProtoMessage()    {}
func (*SaveConfigReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b810c7445c1840d, []int{11}
}

func (m *SaveConfigReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveConfigReply.Unmarshal(m, b)
}
func (m *SaveConfigReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveConfigReply.Marshal(b, m, deterministic)
}
func (m *SaveConfigReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveConfigReply.Merge(m, src)
}
func (m *SaveConfigReply) XXX_Size() int {
	return xxx_messageInfo_SaveConfigReply.Size(m)
}
func (m *SaveConfigReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveConfigReply.DiscardUnknown(m)
}

var xxx_messageInfo_SaveConfigReply proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("vswapi.ModIfnameRequest_Cmd", ModIfnameRequest_Cmd_name, ModIfnameRequest_Cmd_value)
	proto.RegisterEnum("vswapi.ModLinkRequest_Cmd", ModLinkRequest_Cmd_name, ModLinkRequest_Cmd_value)
	proto.RegisterType((*ModIfnameRequest)(nil), "vswapi.ModIfnameRequest")
	proto.RegisterType((*ModIfnameReply)(nil), "vswapi.ModIfnameReply")
	proto.RegisterType((*GetIfnamesRequest)(nil), "vswapi.GetIfnamesRequest")
	proto.RegisterType((*GetIfnamesReply)(nil), "vswapi.GetIfnamesReply")
	proto.RegisterType((*ModLinkRequest)(nil), "vswapi.ModLinkRequest")
	proto.RegisterType((*ModLinkReply)(nil), "vswapi.ModLinkReply")
	proto.RegisterType((*GetLinksRequest)(nil), "vswapi.GetLinksRequest")
	proto.RegisterType((*GetLinksReply)(nil), "vswapi.GetLinksReply")
	proto.RegisterType((*GetStatsRequest)(nil), "vswapi.GetStatsRequest")
	proto.RegisterType((*GetStatsReply)(nil), "vswapi.GetStatsReply")
	proto.RegisterMapType((map[string]uint64)(nil), "vswapi.GetStatsReply.ValuesEntry")
	proto.RegisterType((*SaveConfigRequest)(nil), "vswapi.SaveConfigRequest")
	proto.RegisterType((*SaveConfigReply)(nil), "vswapi.SaveConfigReply")
}

func init() { proto.RegisterFile("vswapi.proto", fileDescriptor_0b810c7445c1840d) }

var fileDescriptor_0b810c7445c1840d = []byte{
	// 500 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xcd, 0xda, 0xa9, 0xdb, 0x4e, 0x4b, 0xba, 0x19, 0x4a, 0x08, 0x16, 0x87, 0xe0, 0x53, 0x0e,
	0xc8, 0x42, 0x41, 0x42, 0x04, 0x09, 0x50, 0x89, 0xad, 0x0a, 0xa9, 0xa4, 0x95, 0x03, 0x45, 0x1c,
	0x0d, 0xde, 0x56, 0x56, 0x12, 0xdb, 0xc4, 0x4e, 0x5a, 0xff, 0x09, 0x0e, 0x5c, 0xf9, 0xb3, 0x68,
	0xd7, 0xeb, 0x78, 0x9d, 0x04, 0x71, 0x9b, 0x99, 0x9d, 0x8f, 0xf7, 0xe6, 0x8d, 0x16, 0x8e, 0x57,
	0xe9, 0x9d, 0x9f, 0x84, 0x76, 0xb2, 0x88, 0xb3, 0x18, 0x8d, 0xc2, 0xb3, 0x7e, 0x13, 0xa0, 0x9f,
	0xe2, 0xe0, 0xe3, 0x4d, 0xe4, 0xcf, 0x99, 0xc7, 0x7e, 0x2e, 0x59, 0x9a, 0xa1, 0x0d, 0xfa, 0x8f,
	0x79, 0xd0, 0x25, 0x3d, 0xd2, 0x6f, 0x0d, 0x9e, 0xda, 0xb2, 0x70, 0x33, 0xcd, 0x1e, 0xcd, 0x03,
	0x8f, 0x27, 0x62, 0x07, 0x8c, 0x50, 0xbc, 0x74, 0xb5, 0x1e, 0xe9, 0x1f, 0x7a, 0xd2, 0xb3, 0x5e,
	0x81, 0x3e, 0x9a, 0x07, 0xb8, 0x0f, 0xfa, 0xf8, 0xf2, 0x8a, 0x36, 0xb8, 0x71, 0xe6, 0x38, 0x94,
	0x70, 0xc3, 0x73, 0xcf, 0xa9, 0x86, 0x00, 0x86, 0xe3, 0x5e, 0xb8, 0x9f, 0x5d, 0xaa, 0xe3, 0x01,
	0x34, 0x27, 0xdf, 0xc6, 0x23, 0xda, 0xb4, 0x28, 0xb4, 0x94, 0x61, 0xc9, 0x2c, 0xb7, 0x1e, 0x42,
	0xfb, 0x9c, 0x65, 0x45, 0x24, 0x95, 0xf3, 0xad, 0xb7, 0x70, 0xa2, 0x06, 0x93, 0x59, 0xae, 0x20,
	0x21, 0x2a, 0x12, 0x44, 0x68, 0x4e, 0xc3, 0x28, 0x90, 0xf8, 0x84, 0x6d, 0xdd, 0x8b, 0x29, 0x17,
	0x61, 0x34, 0x2d, 0x79, 0x3f, 0x57, 0x79, 0x9b, 0x0a, 0x6f, 0x25, 0xe9, 0xff, 0xac, 0x7b, 0x1b,
	0xac, 0x0d, 0xd0, 0xbe, 0x5c, 0x51, 0xc2, 0xf9, 0x39, 0x97, 0x5f, 0xc7, 0x54, 0xb3, 0x5a, 0x70,
	0xbc, 0x6e, 0xca, 0xd9, 0xb5, 0x05, 0x11, 0xee, 0xaf, 0xb9, 0x0d, 0xe1, 0x41, 0x15, 0xe2, 0xcc,
	0x4e, 0x61, 0x2f, 0x8c, 0x02, 0x76, 0x2f, 0xd0, 0xed, 0x79, 0x85, 0xc3, 0x79, 0x29, 0x08, 0x84,
	0x2d, 0xbb, 0x4d, 0x32, 0x3f, 0x5b, 0x77, 0xfb, 0x43, 0x44, 0x3b, 0x19, 0x93, 0xed, 0x6e, 0x17,
	0xf1, 0x32, 0x91, 0x7b, 0x2a, 0x1c, 0x1c, 0x82, 0xb1, 0xf2, 0x67, 0x4b, 0x96, 0x76, 0xb5, 0x9e,
	0xde, 0x3f, 0x1a, 0x3c, 0x2b, 0x77, 0x50, 0x2b, 0xb6, 0xaf, 0x45, 0x8e, 0x1b, 0x65, 0x8b, 0xdc,
	0x93, 0x05, 0xe6, 0x10, 0x8e, 0x94, 0x30, 0x52, 0xd0, 0xa7, 0x2c, 0x97, 0xdd, 0xb9, 0xc9, 0x27,
	0x8a, 0x54, 0x81, 0xb5, 0xe9, 0x15, 0xce, 0x1b, 0xed, 0x35, 0xe1, 0xe2, 0x4e, 0xfc, 0x15, 0x1b,
	0xc5, 0xd1, 0x4d, 0x78, 0x5b, 0x42, 0x6e, 0xc3, 0x89, 0x1a, 0x4c, 0x66, 0xf9, 0xe0, 0x97, 0x0e,
	0xc6, 0x75, 0x7a, 0x77, 0x96, 0x84, 0xf8, 0x1e, 0x0e, 0xd7, 0x17, 0x82, 0xdd, 0x7f, 0x5d, 0xa8,
	0xd9, 0xd9, 0xf1, 0xc2, 0x17, 0xde, 0x40, 0x07, 0xa0, 0xba, 0x1d, 0x7c, 0xa2, 0xf0, 0xac, 0x1f,
	0x99, 0xf9, 0x78, 0xd7, 0x93, 0xe8, 0xf1, 0x82, 0xe0, 0x10, 0xf6, 0xa5, 0x90, 0xd8, 0xd9, 0x7d,
	0x2e, 0xe6, 0xe9, 0x56, 0xbc, 0x00, 0xf0, 0x0e, 0x0e, 0x4a, 0x81, 0x51, 0x9d, 0xa1, 0x5e, 0x81,
	0xf9, 0x68, 0xfb, 0xa1, 0x1c, 0x5d, 0xd4, 0x0b, 0x51, 0x6a, 0xf5, 0xaa, 0xee, 0xb5, 0xfa, 0x4a,
	0x3f, 0x51, 0xff, 0x01, 0xa0, 0xda, 0x6f, 0xb5, 0x80, 0x2d, 0x21, 0xaa, 0x05, 0x6c, 0xc8, 0x61,
	0x35, 0xbe, 0x1b, 0xe2, 0x2f, 0x79, 0xf9, 0x37, 0x00, 0x00, 0xff, 0xff, 0x78, 0xf9, 0x30, 0xff,
	0x5b, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VswApiClient is the client API for VswApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VswApiClient interface {
	ModIfname(ctx context.Context, in *ModIfnameRequest, opts ...grpc.CallOption) (*ModIfnameReply, error)
	GetIfnames(ctx context.Context, in *GetIfnamesRequest, opts ...grpc.CallOption) (VswApi_GetIfnamesClient, error)
	ModLink(ctx context.Context, in *ModLinkRequest, opts ...grpc.CallOption) (*ModLinkReply, error)
	GetLinks(ctx context.Context, in *GetLinksRequest, opts ...grpc.CallOption) (VswApi_GetLinksClient, error)
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (VswApi_GetStatsClient, error)
	SaveConfig(ctx context.Context, in *SaveConfigRequest, opts ...grpc.CallOption) (*SaveConfigReply, error)
}

type vswApiClient struct {
	cc *grpc.ClientConn
}

func NewVswApiClient(cc *grpc.ClientConn) VswApiClient {
	return &vswApiClient{cc}
}

func (c *vswApiClient) ModIfname(ctx context.Context, in *ModIfnameRequest, opts ...grpc.CallOption) (*ModIfnameReply, error) {
	out := new(ModIfnameReply)
	err := c.cc.Invoke(ctx, "/vswapi.VswApi/ModIfname", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vswApiClient) GetIfnames(ctx context.Context, in *GetIfnamesRequest, opts ...grpc.CallOption) (VswApi_GetIfnamesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_VswApi_serviceDesc.Streams[0], "/vswapi.VswApi/GetIfnames", opts...)
	if err != nil {
		return nil, err
	}
	x := &vswApiGetIfnamesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VswApi_GetIfnamesClient interface {
	Recv() (*GetIfnamesReply, error)
	grpc.ClientStream
}

type vswApiGetIfnamesClient struct {
	grpc.ClientStream
}

func (x *vswApiGetIfnamesClient) Recv() (*GetIfnamesReply, error) {
	m := new(GetIfnamesReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vswApiClient) ModLink(ctx context.Context, in *ModLinkRequest, opts ...grpc.CallOption) (*ModLinkReply, error) {
	out := new(ModLinkReply)
	err := c.cc.Invoke(ctx, "/vswapi.VswApi/ModLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vswApiClient) GetLinks(ctx context.Context, in *GetLinksRequest, opts ...grpc.CallOption) (VswApi_GetLinksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_VswApi_serviceDesc.Streams[1], "/vswapi.VswApi/GetLinks", opts...)
	if err != nil {
		return nil, err
	}
	x := &vswApiGetLinksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VswApi_GetLinksClient interface {
	Recv() (*GetLinksReply, error)
	grpc.ClientStream
}

type vswApiGetLinksClient struct {
	grpc.ClientStream
}

func (x *vswApiGetLinksClient) Recv() (*GetLinksReply, error) {
	m := new(GetLinksReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vswApiClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (VswApi_GetStatsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_VswApi_serviceDesc.Streams[2], "/vswapi.VswApi/GetStats", opts...)
	if err != nil {
		return nil, err
	}
	x := &vswApiGetStatsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VswApi_GetStatsClient interface {
	Recv() (*GetStatsReply, error)
	grpc.ClientStream
}

type vswApiGetStatsClient struct {
	grpc.ClientStream
}

func (x *vswApiGetStatsClient) Recv() (*GetStatsReply, error) {
	m := new(GetStatsReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *vswApiClient) SaveConfig(ctx context.Context, in *SaveConfigRequest, opts ...grpc.CallOption) (*SaveConfigReply, error) {
	out := new(SaveConfigReply)
	err := c.cc.Invoke(ctx, "/vswapi.VswApi/SaveConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VswApiServer is the server API for VswApi service.
type VswApiServer interface {
	ModIfname(context.Context, *ModIfnameRequest) (*ModIfnameReply, error)
	GetIfnames(*GetIfnamesRequest, VswApi_GetIfnamesServer) error
	ModLink(context.Context, *ModLinkRequest) (*ModLinkReply, error)
	GetLinks(*GetLinksRequest, VswApi_GetLinksServer) error
	GetStats(*GetStatsRequest, VswApi_GetStatsServer) error
	SaveConfig(context.Context, *SaveConfigRequest) (*SaveConfigReply, error)
}

// UnimplementedVswApiServer can be embedded to have forward compatible implementations.
type UnimplementedVswApiServer struct {
}

func (*UnimplementedVswApiServer) ModIfname(ctx context.Context, req *ModIfnameRequest) (*ModIfnameReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModIfname not implemented")
}
func (*UnimplementedVswApiServer) GetIfnames(req *GetIfnamesRequest, srv VswApi_GetIfnamesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetIfnames not implemented")
}
func (*UnimplementedVswApiServer) ModLink(ctx context.Context, req *ModLinkRequest) (*ModLinkReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModLink not implemented")
}
func (*UnimplementedVswApiServer) GetLinks(req *GetLinksRequest, srv VswApi_GetLinksServer) error {
	return status.Errorf(codes.Unimplemented, "method GetLinks not implemented")
}
func (*UnimplementedVswApiServer) GetStats(req *GetStatsRequest, srv VswApi_GetStatsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (*UnimplementedVswApiServer) SaveConfig(ctx context.Context, req *SaveConfigRequest) (*SaveConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveConfig not implemented")
}

func RegisterVswApiServer(s *grpc.Server, srv VswApiServer) {
	s.RegisterService(&_VswApi_serviceDesc, srv)
}

func _VswApi_ModIfname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModIfnameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VswApiServer).ModIfname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vswapi.VswApi/ModIfname",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VswApiServer).ModIfname(ctx, req.(*ModIfnameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VswApi_GetIfnames_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetIfnamesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VswApiServer).GetIfnames(m, &vswApiGetIfnamesServer{stream})
}

type VswApi_GetIfnamesServer interface {
	Send(*GetIfnamesReply) error
	grpc.ServerStream
}

type vswApiGetIfnamesServer struct {
	grpc.ServerStream
}

func (x *vswApiGetIfnamesServer) Send(m *GetIfnamesReply) error {
	return x.ServerStream.SendMsg(m)
}

func _VswApi_ModLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VswApiServer).ModLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vswapi.VswApi/ModLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VswApiServer).ModLink(ctx, req.(*ModLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VswApi_GetLinks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLinksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VswApiServer).GetLinks(m, &vswApiGetLinksServer{stream})
}

type VswApi_GetLinksServer interface {
	Send(*GetLinksReply) error
	grpc.ServerStream
}

type vswApiGetLinksServer struct {
	grpc.ServerStream
}

func (x *vswApiGetLinksServer) Send(m *GetLinksReply) error {
	return x.ServerStream.SendMsg(m)
}

func _VswApi_GetStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetStatsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VswApiServer).GetStats(m, &vswApiGetStatsServer{stream})
}

type VswApi_GetStatsServer interface {
	Send(*GetStatsReply) error
	grpc.ServerStream
}

type vswApiGetStatsServer struct {
	grpc.ServerStream
}

func (x *vswApiGetStatsServer) Send(m *GetStatsReply) error {
	return x.ServerStream.SendMsg(m)
}

func _VswApi_SaveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VswApiServer).SaveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vswapi.VswApi/SaveConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VswApiServer).SaveConfig(ctx, req.(*SaveConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VswApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vswapi.VswApi",
	HandlerType: (*VswApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ModIfname",
			Handler:    _VswApi_ModIfname_Handler,
		},
		{
			MethodName: "ModLink",
			Handler:    _VswApi_ModLink_Handler,
		},
		{
			MethodName: "SaveConfig",
			Handler:    _VswApi_SaveConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetIfnames",
			Handler:       _VswApi_GetIfnames_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetLinks",
			Handler:       _VswApi_GetLinks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetStats",
			Handler:       _VswApi_GetStats_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "vswapi.proto",
}
