# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import vswapi_pb2 as vswapi__pb2


class VswApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ModIfname = channel.unary_unary(
        '/vswapi.VswApi/ModIfname',
        request_serializer=vswapi__pb2.ModIfnameRequest.SerializeToString,
        response_deserializer=vswapi__pb2.ModIfnameReply.FromString,
        )
    self.GetIfnames = channel.unary_stream(
        '/vswapi.VswApi/GetIfnames',
        request_serializer=vswapi__pb2.GetIfnamesRequest.SerializeToString,
        response_deserializer=vswapi__pb2.GetIfnamesReply.FromString,
        )
    self.ModLink = channel.unary_unary(
        '/vswapi.VswApi/ModLink',
        request_serializer=vswapi__pb2.ModLinkRequest.SerializeToString,
        response_deserializer=vswapi__pb2.ModLinkReply.FromString,
        )
    self.GetLinks = channel.unary_stream(
        '/vswapi.VswApi/GetLinks',
        request_serializer=vswapi__pb2.GetLinksRequest.SerializeToString,
        response_deserializer=vswapi__pb2.GetLinksReply.FromString,
        )
    self.GetStats = channel.unary_stream(
        '/vswapi.VswApi/GetStats',
        request_serializer=vswapi__pb2.GetStatsRequest.SerializeToString,
        response_deserializer=vswapi__pb2.GetStatsReply.FromString,
        )
    self.SaveConfig = channel.unary_unary(
        '/vswapi.VswApi/SaveConfig',
        request_serializer=vswapi__pb2.SaveConfigRequest.SerializeToString,
        response_deserializer=vswapi__pb2.SaveConfigReply.FromString,
        )


class VswApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ModIfname(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetIfnames(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ModLink(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetLinks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetStats(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SaveConfig(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VswApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ModIfname': grpc.unary_unary_rpc_method_handler(
          servicer.ModIfname,
          request_deserializer=vswapi__pb2.ModIfnameRequest.FromString,
          response_serializer=vswapi__pb2.ModIfnameReply.SerializeToString,
      ),
      'GetIfnames': grpc.unary_stream_rpc_method_handler(
          servicer.GetIfnames,
          request_deserializer=vswapi__pb2.GetIfnamesRequest.FromString,
          response_serializer=vswapi__pb2.GetIfnamesReply.SerializeToString,
      ),
      'ModLink': grpc.unary_unary_rpc_method_handler(
          servicer.ModLink,
          request_deserializer=vswapi__pb2.ModLinkRequest.FromString,
          response_serializer=vswapi__pb2.ModLinkReply.SerializeToString,
      ),
      'GetLinks': grpc.unary_stream_rpc_method_handler(
          servicer.GetLinks,
          request_deserializer=vswapi__pb2.GetLinksRequest.FromString,
          response_serializer=vswapi__pb2.GetLinksReply.SerializeToString,
      ),
      'GetStats': grpc.unary_stream_rpc_method_handler(
          servicer.GetStats,
          request_deserializer=vswapi__pb2.GetStatsRequest.FromString,
          response_serializer=vswapi__pb2.GetStatsReply.SerializeToString,
      ),
      'SaveConfig': grpc.unary_unary_rpc_method_handler(
          servicer.SaveConfig,
          request_deserializer=vswapi__pb2.SaveConfigRequest.FromString,
          response_serializer=vswapi__pb2.SaveConfigReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'vswapi.VswApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
