# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vswapi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vswapi.proto',
  package='vswapi',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cvswapi.proto\x12\x06vswapi\"\x85\x01\n\x10ModIfnameRequest\x12)\n\x03\x63md\x18\x01 \x01(\x0e\x32\x1c.vswapi.ModIfnameRequest.Cmd\x12\x0e\n\x06ifname\x18\x02 \x01(\t\"6\n\x03\x43md\x12\x07\n\x03NOP\x10\x00\x12\x07\n\x03\x41\x44\x44\x10\x01\x12\x07\n\x03REG\x10\x02\x12\n\n\x06\x44\x45LETE\x10\x03\x12\x08\n\x04SYNC\x10\x04\"\x10\n\x0eModIfnameReply\"\x13\n\x11GetIfnamesRequest\"/\n\x0fGetIfnamesReply\x12\x0e\n\x06ifname\x18\x01 \x01(\t\x12\x0c\n\x04kind\x18\x02 \x01(\t\"k\n\x0eModLinkRequest\x12\'\n\x03\x63md\x18\x01 \x01(\x0e\x32\x1a.vswapi.ModLinkRequest.Cmd\x12\x0e\n\x06ifname\x18\x02 \x01(\t\" \n\x03\x43md\x12\x07\n\x03NOP\x10\x00\x12\x06\n\x02UP\x10\x01\x12\x08\n\x04\x44OWN\x10\x02\"\x0e\n\x0cModLinkReply\"\x11\n\x0fGetLinksRequest\",\n\rGetLinksReply\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x11\n\x0fGetStatsRequest\"\x80\x01\n\rGetStatsReply\x12\r\n\x05group\x18\x01 \x01(\t\x12\x31\n\x06values\x18\x02 \x03(\x0b\x32!.vswapi.GetStatsReply.ValuesEntry\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x04:\x02\x38\x01\"\x13\n\x11SaveConfigRequest\"\x11\n\x0fSaveConfigReply2\x8e\x03\n\x06VswApi\x12?\n\tModIfname\x12\x18.vswapi.ModIfnameRequest\x1a\x16.vswapi.ModIfnameReply\"\x00\x12\x44\n\nGetIfnames\x12\x19.vswapi.GetIfnamesRequest\x1a\x17.vswapi.GetIfnamesReply\"\x00\x30\x01\x12\x39\n\x07ModLink\x12\x16.vswapi.ModLinkRequest\x1a\x14.vswapi.ModLinkReply\"\x00\x12>\n\x08GetLinks\x12\x17.vswapi.GetLinksRequest\x1a\x15.vswapi.GetLinksReply\"\x00\x30\x01\x12>\n\x08GetStats\x12\x17.vswapi.GetStatsRequest\x1a\x15.vswapi.GetStatsReply\"\x00\x30\x01\x12\x42\n\nSaveConfig\x12\x19.vswapi.SaveConfigRequest\x1a\x17.vswapi.SaveConfigReply\"\x00\x62\x06proto3')
)



_MODIFNAMEREQUEST_CMD = _descriptor.EnumDescriptor(
  name='Cmd',
  full_name='vswapi.ModIfnameRequest.Cmd',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOP', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REG', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SYNC', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=104,
  serialized_end=158,
)
_sym_db.RegisterEnumDescriptor(_MODIFNAMEREQUEST_CMD)

_MODLINKREQUEST_CMD = _descriptor.EnumDescriptor(
  name='Cmd',
  full_name='vswapi.ModLinkRequest.Cmd',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOP', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UP', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOWN', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=323,
  serialized_end=355,
)
_sym_db.RegisterEnumDescriptor(_MODLINKREQUEST_CMD)


_MODIFNAMEREQUEST = _descriptor.Descriptor(
  name='ModIfnameRequest',
  full_name='vswapi.ModIfnameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='vswapi.ModIfnameRequest.cmd', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ifname', full_name='vswapi.ModIfnameRequest.ifname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MODIFNAMEREQUEST_CMD,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=158,
)


_MODIFNAMEREPLY = _descriptor.Descriptor(
  name='ModIfnameReply',
  full_name='vswapi.ModIfnameReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=176,
)


_GETIFNAMESREQUEST = _descriptor.Descriptor(
  name='GetIfnamesRequest',
  full_name='vswapi.GetIfnamesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=197,
)


_GETIFNAMESREPLY = _descriptor.Descriptor(
  name='GetIfnamesReply',
  full_name='vswapi.GetIfnamesReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ifname', full_name='vswapi.GetIfnamesReply.ifname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kind', full_name='vswapi.GetIfnamesReply.kind', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=246,
)


_MODLINKREQUEST = _descriptor.Descriptor(
  name='ModLinkRequest',
  full_name='vswapi.ModLinkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='vswapi.ModLinkRequest.cmd', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ifname', full_name='vswapi.ModLinkRequest.ifname', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MODLINKREQUEST_CMD,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=355,
)


_MODLINKREPLY = _descriptor.Descriptor(
  name='ModLinkReply',
  full_name='vswapi.ModLinkReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=357,
  serialized_end=371,
)


_GETLINKSREQUEST = _descriptor.Descriptor(
  name='GetLinksRequest',
  full_name='vswapi.GetLinksRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=390,
)


_GETLINKSREPLY = _descriptor.Descriptor(
  name='GetLinksReply',
  full_name='vswapi.GetLinksReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='vswapi.GetLinksReply.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='vswapi.GetLinksReply.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=436,
)


_GETSTATSREQUEST = _descriptor.Descriptor(
  name='GetStatsRequest',
  full_name='vswapi.GetStatsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=438,
  serialized_end=455,
)


_GETSTATSREPLY_VALUESENTRY = _descriptor.Descriptor(
  name='ValuesEntry',
  full_name='vswapi.GetStatsReply.ValuesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='vswapi.GetStatsReply.ValuesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='vswapi.GetStatsReply.ValuesEntry.value', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=586,
)

_GETSTATSREPLY = _descriptor.Descriptor(
  name='GetStatsReply',
  full_name='vswapi.GetStatsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group', full_name='vswapi.GetStatsReply.group', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='vswapi.GetStatsReply.values', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GETSTATSREPLY_VALUESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=458,
  serialized_end=586,
)


_SAVECONFIGREQUEST = _descriptor.Descriptor(
  name='SaveConfigRequest',
  full_name='vswapi.SaveConfigRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=588,
  serialized_end=607,
)


_SAVECONFIGREPLY = _descriptor.Descriptor(
  name='SaveConfigReply',
  full_name='vswapi.SaveConfigReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=609,
  serialized_end=626,
)

_MODIFNAMEREQUEST.fields_by_name['cmd'].enum_type = _MODIFNAMEREQUEST_CMD
_MODIFNAMEREQUEST_CMD.containing_type = _MODIFNAMEREQUEST
_MODLINKREQUEST.fields_by_name['cmd'].enum_type = _MODLINKREQUEST_CMD
_MODLINKREQUEST_CMD.containing_type = _MODLINKREQUEST
_GETSTATSREPLY_VALUESENTRY.containing_type = _GETSTATSREPLY
_GETSTATSREPLY.fields_by_name['values'].message_type = _GETSTATSREPLY_VALUESENTRY
DESCRIPTOR.message_types_by_name['ModIfnameRequest'] = _MODIFNAMEREQUEST
DESCRIPTOR.message_types_by_name['ModIfnameReply'] = _MODIFNAMEREPLY
DESCRIPTOR.message_types_by_name['GetIfnamesRequest'] = _GETIFNAMESREQUEST
DESCRIPTOR.message_types_by_name['GetIfnamesReply'] = _GETIFNAMESREPLY
DESCRIPTOR.message_types_by_name['ModLinkRequest'] = _MODLINKREQUEST
DESCRIPTOR.message_types_by_name['ModLinkReply'] = _MODLINKREPLY
DESCRIPTOR.message_types_by_name['GetLinksRequest'] = _GETLINKSREQUEST
DESCRIPTOR.message_types_by_name['GetLinksReply'] = _GETLINKSREPLY
DESCRIPTOR.message_types_by_name['GetStatsRequest'] = _GETSTATSREQUEST
DESCRIPTOR.message_types_by_name['GetStatsReply'] = _GETSTATSREPLY
DESCRIPTOR.message_types_by_name['SaveConfigRequest'] = _SAVECONFIGREQUEST
DESCRIPTOR.message_types_by_name['SaveConfigReply'] = _SAVECONFIGREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModIfnameRequest = _reflection.GeneratedProtocolMessageType('ModIfnameRequest', (_message.Message,), dict(
  DESCRIPTOR = _MODIFNAMEREQUEST,
  __module__ = 'vswapi_pb2'
  # @@protoc_insertion_point(class_scope:vswapi.ModIfnameRequest)
  ))
_sym_db.RegisterMessage(ModIfnameRequest)

ModIfnameReply = _reflection.GeneratedProtocolMessageType('ModIfnameReply', (_message.Message,), dict(
  DESCRIPTOR = _MODIFNAMEREPLY,
  __module__ = 'vswapi_pb2'
  # @@protoc_insertion_point(class_scope:vswapi.ModIfnameReply)
  ))
_sym_db.RegisterMessage(ModIfnameReply)

GetIfnamesRequest = _reflection.GeneratedProtocolMessageType('GetIfnamesRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETIFNAMESREQUEST,
  __module__ = 'vswapi_pb2'
  # @@protoc_insertion_point(class_scope:vswapi.GetIfnamesRequest)
  ))
_sym_db.RegisterMessage(GetIfnamesRequest)

GetIfnamesReply = _reflection.GeneratedProtocolMessageType('GetIfnamesReply', (_message.Message,), dict(
  DESCRIPTOR = _GETIFNAMESREPLY,
  __module__ = 'vswapi_pb2'
  # @@protoc_insertion_point(class_scope:vswapi.GetIfnamesReply)
  ))
_sym_db.RegisterMessage(GetIfnamesReply)

ModLinkRequest = _reflection.GeneratedProtocolMessageType('ModLinkRequest', (_message.Message,), dict(
  DESCRIPTOR = _MODLINKREQUEST,
  __module__ = 'vswapi_pb2'
  # @@protoc_insertion_point(class_scope:vswapi.ModLinkRequest)
  ))
_sym_db.RegisterMessage(ModLinkRequest)

ModLinkReply = _reflection.GeneratedProtocolMessageType('ModLinkReply', (_message.Message,), dict(
  DESCRIPTOR = _MODLINKREPLY,
  __module__ = 'vswapi_pb2'
  # @@protoc_insertion_point(class_scope:vswapi.ModLinkReply)
  ))
_sym_db.RegisterMessage(ModLinkReply)

GetLinksRequest = _reflection.GeneratedProtocolMessageType('GetLinksRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETLINKSREQUEST,
  __module__ = 'vswapi_pb2'
  # @@protoc_insertion_point(class_scope:vswapi.GetLinksRequest)
  ))
_sym_db.RegisterMessage(GetLinksRequest)

GetLinksReply = _reflection.GeneratedProtocolMessageType('GetLinksReply', (_message.Message,), dict(
  DESCRIPTOR = _GETLINKSREPLY,
  __module__ = 'vswapi_pb2'
  # @@protoc_insertion_point(class_scope:vswapi.GetLinksReply)
  ))
_sym_db.RegisterMessage(GetLinksReply)

GetStatsRequest = _reflection.GeneratedProtocolMessageType('GetStatsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETSTATSREQUEST,
  __module__ = 'vswapi_pb2'
  # @@protoc_insertion_point(class_scope:vswapi.GetStatsRequest)
  ))
_sym_db.RegisterMessage(GetStatsRequest)

GetStatsReply = _reflection.GeneratedProtocolMessageType('GetStatsReply', (_message.Message,), dict(

  ValuesEntry = _reflection.GeneratedProtocolMessageType('ValuesEntry', (_message.Message,), dict(
    DESCRIPTOR = _GETSTATSREPLY_VALUESENTRY,
    __module__ = 'vswapi_pb2'
    # @@protoc_insertion_point(class_scope:vswapi.GetStatsReply.ValuesEntry)
    ))
  ,
  DESCRIPTOR = _GETSTATSREPLY,
  __module__ = 'vswapi_pb2'
  # @@protoc_insertion_point(class_scope:vswapi.GetStatsReply)
  ))
_sym_db.RegisterMessage(GetStatsReply)
_sym_db.RegisterMessage(GetStatsReply.ValuesEntry)

SaveConfigRequest = _reflection.GeneratedProtocolMessageType('SaveConfigRequest', (_message.Message,), dict(
  DESCRIPTOR = _SAVECONFIGREQUEST,
  __module__ = 'vswapi_pb2'
  # @@protoc_insertion_point(class_scope:vswapi.SaveConfigRequest)
  ))
_sym_db.RegisterMessage(SaveConfigRequest)

SaveConfigReply = _reflection.GeneratedProtocolMessageType('SaveConfigReply', (_message.Message,), dict(
  DESCRIPTOR = _SAVECONFIGREPLY,
  __module__ = 'vswapi_pb2'
  # @@protoc_insertion_point(class_scope:vswapi.SaveConfigReply)
  ))
_sym_db.RegisterMessage(SaveConfigReply)


_GETSTATSREPLY_VALUESENTRY._options = None

_VSWAPI = _descriptor.ServiceDescriptor(
  name='VswApi',
  full_name='vswapi.VswApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=629,
  serialized_end=1027,
  methods=[
  _descriptor.MethodDescriptor(
    name='ModIfname',
    full_name='vswapi.VswApi.ModIfname',
    index=0,
    containing_service=None,
    input_type=_MODIFNAMEREQUEST,
    output_type=_MODIFNAMEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetIfnames',
    full_name='vswapi.VswApi.GetIfnames',
    index=1,
    containing_service=None,
    input_type=_GETIFNAMESREQUEST,
    output_type=_GETIFNAMESREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ModLink',
    full_name='vswapi.VswApi.ModLink',
    index=2,
    containing_service=None,
    input_type=_MODLINKREQUEST,
    output_type=_MODLINKREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetLinks',
    full_name='vswapi.VswApi.GetLinks',
    index=3,
    containing_service=None,
    input_type=_GETLINKSREQUEST,
    output_type=_GETLINKSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetStats',
    full_name='vswapi.VswApi.GetStats',
    index=4,
    containing_service=None,
    input_type=_GETSTATSREQUEST,
    output_type=_GETSTATSREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SaveConfig',
    full_name='vswapi.VswApi.SaveConfig',
    index=5,
    containing_service=None,
    input_type=_SAVECONFIGREQUEST,
    output_type=_SAVECONFIGREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VSWAPI)

DESCRIPTOR.services_by_name['VswApi'] = _VSWAPI

# @@protoc_insertion_point(module_scope)
