#! /bin/sh
# -*- coding: utf-8; mode: shell-script -*-

# Copyright (C) 2018 Nippon Telegraph and Telephone Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

do_insmod() {
    
    mknod  /dev/linux-kernel-bde c 127 0 || true
    mknod  /dev/linux-user-bde   c 126 0 || true
    mknod  /dev/linux-bcm-knet   c 122 0 || true

    insmod /etc/opennsl/drivers/linux-kernel-bde.ko maxpayload=128
    insmod /etc/opennsl/drivers/linux-user-bde.ko
    insmod /etc/opennsl/drivers/linux-bcm-knet.ko
}

do_rmmod() {
    rmmod linux-bcm-knet   || true
    rmmod linux-user-bde   || true
    rmmod linux-kernel-bde || true
}

do_usage() {
    echo "$0 <insmod | rmmod>"
}

case $1 in
    insmod) do_insmod;;
    rmmod)  do_rmmod;;
    *)      do_usage;;
esac
